steps:
  - name: 'bash'
    args: ['npm', 'test'] 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/broyal-demo-354814/build-demo', '.']
options:
  pool:
    name: 'projects/broyal-demo-354814/locations/us-central1/workerPools/demo-pool'